# configuration file for Weston
[core]
require-outputs=none

[shell]
background-image=/etc/PFR_LOGO_BLACK.png
background-type=centered
background-color=0xffffffff

# [launcher]
# icon=/usr/share/weston/terminal.png
# path=/usr/bin/weston-terminal

# [launcher]
# icon=/etc/media/Qdemo.png
# path=/usr/bin/Qdemo